In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name":["Alice", "Bob", "Charlie", "Daksh", "Karan"],
    "Age":[25,30,27,24,29],
    "Gender":['F','M','M','M','M']
}

In [ ]:
#DataFrame
df=pd.DataFrame(data)
df.head()

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   27      M
3    Daksh   24      M
4    Karan   29      M

In [ ]:
df.info(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Gender  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [ ]:
#selection of data
df['Age'].head(3)

0    25
1    30
2    27
Name: Age, dtype: int64

In [ ]:
df[['Age','Gender']].tail()

   Age Gender
0   25      F
1   30      M
2   27      M
3   24      M
4   29      M

In [ ]:
df.loc[0]

Name      Alice
Age          25
Gender        F
Name: 0, dtype: object